{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sendbird.sdk",
    "module": "sendbird-desk-android-sdk",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.7.aar",
          "url": "sendbird-desk-android-sdk-1.1.7.aar",
          "size": 50746,
          "sha512": "2b40e500bb4bbf1264b4adf42e333a213a7032ae4a308bbee15d735f299b464225fce3084a568cf03ee477044a27e3016220567f0bcb3ec3f1f6b7fd2187be34",
          "sha256": "fda0a616a194acf36bb49d50c33f89782b052405ba2737f0b9d656d7ac0c4dfe",
          "sha1": "54fbff964b840710c77bd220a8c7767b24648fa4",
          "md5": "67def99de8d2675abd03e41619873689"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.24.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.7.aar",
          "url": "sendbird-desk-android-sdk-1.1.7.aar",
          "size": 50746,
          "sha512": "2b40e500bb4bbf1264b4adf42e333a213a7032ae4a308bbee15d735f299b464225fce3084a568cf03ee477044a27e3016220567f0bcb3ec3f1f6b7fd2187be34",
          "sha256": "fda0a616a194acf36bb49d50c33f89782b052405ba2737f0b9d656d7ac0c4dfe",
          "sha1": "54fbff964b840710c77bd220a8c7767b24648fa4",
          "md5": "67def99de8d2675abd03e41619873689"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.7-sources.jar",
          "url": "sendbird-desk-android-sdk-1.1.7-sources.jar",
          "size": 18625,
          "sha512": "147730ff20d33ec6cbb4399b8bd67a9fae601647a0de1beb3b0901df87c549537f5f917d9d2688ca024fb5d6493d4cdd4068002446cb27dc38f3d9945b8bcf0c",
          "sha256": "1d839e0a875ecc3030c4d5b1fbc8e3f5e80219b58755a4bb6d93803054e96e94",
          "sha1": "9221dd3b8f7592c8889fecf9899e38275e760205",
          "md5": "0137630bb0b6559f3faa4509b13cb5a3"
        }
      ]
    }
  ]
}
