{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sendbird.sdk",
    "module": "sendbird-desk-android-sdk",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.0.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.1.aar",
          "url": "sendbird-desk-android-sdk-1.1.1.aar",
          "size": 49740,
          "sha512": "73023be11b56a8f9a79a48883ae09da292705d1612a035fe24a61c868d48303a61514b975111f8473b46d12fcc07944b3b01380998040c3609cd9935452d6307",
          "sha256": "430faf6f294e74b9d94c0ced90ed993fd931f9c8ac1090c05a235825550fed57",
          "sha1": "f8ef4a707c7def6b947a62087426e691c772630f",
          "md5": "ee309f6bc3ceeb1e76bdae889f155d11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.0.9"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.1.aar",
          "url": "sendbird-desk-android-sdk-1.1.1.aar",
          "size": 49740,
          "sha512": "73023be11b56a8f9a79a48883ae09da292705d1612a035fe24a61c868d48303a61514b975111f8473b46d12fcc07944b3b01380998040c3609cd9935452d6307",
          "sha256": "430faf6f294e74b9d94c0ced90ed993fd931f9c8ac1090c05a235825550fed57",
          "sha1": "f8ef4a707c7def6b947a62087426e691c772630f",
          "md5": "ee309f6bc3ceeb1e76bdae889f155d11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.1-sources.jar",
          "url": "sendbird-desk-android-sdk-1.1.1-sources.jar",
          "size": 17642,
          "sha512": "d26fe8a96af7761c2d3a82962f1e588b7987070a5cd473e0c979a594d4c5e3c51b3884088320cdf5c63bf6500d9ab99e6c44757ced8797a03d1775b8c671b3a1",
          "sha256": "2231fa0167b5c79488792eb6895006371cac1b0567d60e8f55abe768f26630b7",
          "sha1": "5322ed5e75e30286e70549774093659f24ad6420",
          "md5": "cea54140a58ba3bf301d02971dfea0b9"
        }
      ]
    }
  ]
}
