{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sendbird.sdk",
    "module": "sendbird-desk-android-sdk",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.3.aar",
          "url": "sendbird-desk-android-sdk-1.1.3.aar",
          "size": 50589,
          "sha512": "b69f4248a7c09242e3cff783bd2ab31ec57f82c891445d9153779a5e7c5296ca0734393d10eee7859ed9a982531f0d33c1434b2f0d9d11290b48bf7b6cf8ef93",
          "sha256": "6d1e780a2b6afa066f9f38fb34ebf2a707361a12ea7131797f8565fb7b8df3d0",
          "sha1": "b8f8d432950ef8b414851e6b202c908ac0ed8f0b",
          "md5": "b80b974a7ac48182b8e036f1a3f3e551"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.sendbird.sdk",
          "module": "sendbird-chat",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.3.aar",
          "url": "sendbird-desk-android-sdk-1.1.3.aar",
          "size": 50589,
          "sha512": "b69f4248a7c09242e3cff783bd2ab31ec57f82c891445d9153779a5e7c5296ca0734393d10eee7859ed9a982531f0d33c1434b2f0d9d11290b48bf7b6cf8ef93",
          "sha256": "6d1e780a2b6afa066f9f38fb34ebf2a707361a12ea7131797f8565fb7b8df3d0",
          "sha1": "b8f8d432950ef8b414851e6b202c908ac0ed8f0b",
          "md5": "b80b974a7ac48182b8e036f1a3f3e551"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sendbird-desk-android-sdk-1.1.3-sources.jar",
          "url": "sendbird-desk-android-sdk-1.1.3-sources.jar",
          "size": 18036,
          "sha512": "ea1a991d9f0dad16d88a3a6f0225dc487cdbae70d0787f17f9615c80402237416c3414286b45ad70441e83e496c21fd6f935b8014ce74f9d991db723a26be661",
          "sha256": "026c6b934a31a5296f7a2e36200fdd307b3b41d4a4e8bc276b73014ea6127fd0",
          "sha1": "d3f18c4ec2169577ee184cfe183fc76303dfbda7",
          "md5": "b64ebd74e2fb60e6496d79d9bb0135c1"
        }
      ]
    }
  ]
}
